#!/bin/sh                                                                                                                                                                                                                        

                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
PORT="$1"                                                                                                                                                                                                                        
                                                                                                                                                                                                                                 
IFACE="$2"                                                                                                                                                                                                                       
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
attempt=1                                                                                                                                                                                                                        
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
while [ "$attempt" -le 30 ]; do                                                                                                                                                                                                  
                                                                                                                                                                                                                                 
    echo "Trying to set qBittorrent port to ${PORT} (attempt ${attempt}/30)"                                                                                                                                                     
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
    if wget -O /dev/null -nv --retry-connrefused --post-data="json={\"listen_port\":${PORT},\"current_network_interface\":\"${IFACE}\",\"random_port\":false,\"upnp\":false}" "http://127.0.0.1:8080/api/v2/app/setPreferences"; 
then                                                                                                                                                                                                                             
                                                                                                                                                                                                                                 
        echo "Successfully set qBittorrent port to ${PORT}"                                                                                                                                                                      
                                                                                                                                                                                                                                 
        exit 0                                                                                                                                                                                                                   
                                                                                                                                                                                                                                 
    fi                                                                                                                                                                                                                           
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
    attempt=$((attempt + 1))                                                                                                                                                                                                     
                                                                                                                                                                                                                                 
    sleep 2                                                                                                                                                                                                                      
                                                                                                                                                                                                                                 
done                                                                                                                                                                                                                             
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                 
echo "Failed to update qBittorrent after 30 attempts"                                                                                                                                                                            
                                                                                                                                                                                                                                 
exit 1
